start_date: '2004-01'       # Start date for the analysis
VW: True                    # Value-weighted flag
SKIP: False                  # Skip flag
rebalance: 6                # Rebalance frequency in months