# Tweakable parameters for run_all=True
start_date: '2004-01'       # Start date for the analysis
run_all: True               # Run every data flag 
verbose: False               # Verbose flag for detailed output
VW: True                    # Value-weighted flag
SKIP: False                 # Skip flag
flip: False                 # flip flag
rebalance: 6                # Rebalance frequency in months

# Only tweakable for run_all=False
model_no: 8                 # Model number (0, 1, 7, 8 )
