# Configuration file for every tests

start_date: '2004-02'       # + 1 month after the modified strategy

VW: True                    # Value-weighted flag
SKIP: False                 # Skip flag
model_no: 1                 # Model number (0, 1, 7, 8)
reversed: False             # Reversed flag

mode: 'ALL'              # Mode 'ALL', 'returns', 'longs', 'shorts'
detailed: False              # See market and modified